import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Smart Home Automation",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gradient-to-br h-screen from-gray-800 via-gray-900 to-black ${inter.className} text-white`}>
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
